apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-gatekeeper-disallowed-registries
policyDefaults:
  namespace: default
policies:
  - name: disallowed-registries
    manifests:
      - path: ../../../open-policy-agent/trusted-image-sources/disallowed-registries/template.yaml
      - path: ../../../open-policy-agent/trusted-image-sources/disallowed-registries/constraint.yaml
    remediationAction: enforce
    placement:
      clusterSelector:
        matchExpressions:
          - {key: environment, operator: In, values: ["dev"]}
