apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: ocpdefaultscc
  annotations:
    description: Block editing of default Openshift scc. Copy them and update as required.
spec:
  crd:
    spec:
      names:
        kind: OcpDefaultScc
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package ocpdefaultscc

        violation[{"msg": msg}, "details": {}] {
          scc := input.review.object.metadata.name
          default_scc(scc)
          msg := sprintf("Modification of %v scc is forbidden. Please create a new ssc with required configurations", [scc])
        }

        default_scc(scc) {
            input.parameters.defaultScc[_] == "*"
        }
        default_scc(scc) {
            input.parameters.defaultScc[_] == scc
        }
        default_scc(scc) {
            startswith(scc, trim(input.parameters.defaultScc[_], "*"))
        }
